version: '3.8'
services:
  main:    
    build: { context: . }
    container_name: mobx-orm
    ports:
      - 9222:9222 
      - 9229:9229 
    user: "${UID:-1000}:0"
    volumes:
      - .:/app
    stdin_open: true  # docker run -i
    tty       : true  # docker run -t
    command: sh -c "yarn install && sh"
