version: '3.4'

services:
  front:
    build: 
      context: .
    volumes:
      - .:/app
    ports:
      - 9229:9229
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - CHOKIDAR_USEPOLLING=true
    entrypoint: ["sh", "-c", "yarn install && yarn build"]

    # entrypoint: ["sh", "-c", "yarn install && yarn e2e"]
    # entrypoint: ["sh", "-c", "yarn install && node node_modules/.bin/jest --testMatch='**/e2e/**/passports.ts'"]
    # entrypoint: ["sh", "-c", "yarn install && node --inspect-brk=0.0.0.0 node_modules/.bin/jest --runInBand --testMatch='**/e2e/**/chat.ts'"]

    # entrypoint: ["sh", "-c", "yarn install && yarn test"]
    # entrypoint: ["sh", "-c", "yarn install && node node_modules/.bin/jest --testMatch='**/src/**/local.spec.ts'"]
    # entrypoint: ["sh", "-c", "yarn install && node --inspect-brk=0.0.0.0 node_modules/.bin/jest --runInBand --testMatch='**/src/**/many.spec.ts'"]
    # entrypoint: ["sh", "-c", "yarn install && node --inspect-brk=0.0.0.0 node_modules/.bin/jest --runInBand"]
    # chrome://inspect/#devices